notify-slack: Exit with success even if Slack message fails
In our pathogen workflows, the Slack notifications are usually a
nice-to-have feature that are not essential to the workflow. This
changes the script to exit with success even if there was an error
when sending the Slack message.

diff --git a/notify-slack b/notify-slack
--- a/notify-slack
+++ b/notify-slack
@@ -77,4 +77,7 @@ send_slack_message() {
     fi
 }
 
-send_slack_message
+if ! send_slack_message; then
+    echo "Sending Slack message failed, but exiting with success anyway."
+    exit 0
+fi
